spring:
  application:
    name: eureka-school-service
server:
  port: 9012
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9021/eureka/,http://localhost:9022/eureka/
feign:
  compression:
    response:
      enabled: true
  hystrix:
    enabled: true