spring:
  application:
    name: eureka-user-service
server:
  port: 9011
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9021/eureka/,http://localhost:9022/eureka/