spring:
  application:
    name: eureka-school-order
server:
  port: 9013
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9021/eureka/,http://localhost:9022/eureka/