spring:
  application:
    name: eureka-zuul
server:
  port: 9031
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9021/eureka/,http://localhost:9022/eureka/
zuul:
  routes:
    user:
      path: /user/**
      serviceId: eureka-user-service
    school:
      path: /school/**
      serviceId: eureka-school-service